//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentanaXMLWS.PracticaWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PracticaWS.PracticaWSSoap")]
    public interface PracticaWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LeeXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeeXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LeeXMLAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PracticaWSSoapChannel : VentanaXMLWS.PracticaWS.PracticaWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PracticaWSSoapClient : System.ServiceModel.ClientBase<VentanaXMLWS.PracticaWS.PracticaWSSoap>, VentanaXMLWS.PracticaWS.PracticaWSSoap {
        
        public PracticaWSSoapClient() {
        }
        
        public PracticaWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PracticaWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticaWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable LeeXML() {
            return base.Channel.LeeXML();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LeeXMLAsync() {
            return base.Channel.LeeXMLAsync();
        }
    }
}
