//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentanaPrincipalWS.prueba {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="prueba.WSXMLSoap")]
    public interface WSXMLSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LeeXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeeXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LeeXMLAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSXMLSoapChannel : VentanaPrincipalWS.prueba.WSXMLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSXMLSoapClient : System.ServiceModel.ClientBase<VentanaPrincipalWS.prueba.WSXMLSoap>, VentanaPrincipalWS.prueba.WSXMLSoap {
        
        public WSXMLSoapClient() {
        }
        
        public WSXMLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSXMLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSXMLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSXMLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable LeeXML() {
            return base.Channel.LeeXML();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LeeXMLAsync() {
            return base.Channel.LeeXMLAsync();
        }
    }
}
